CC	:= gcc
CFLAGS := -Wall -Werror -g -O0 -pthread

.PHONY: assignment1 clean

assignment1: assignment1.c
	$(CC) $(CFLAGS) -o assignment1 assignment1.c

assignment2: assignment2.c
	$(CC) $(CFLAGS) -o assignment2 assignment2.c

assignment3: assignment3.c
	$(CC) $(CFLAGS) -o assignment3 assignment3.c
clean:
	rm -rf assignment1  assignment2 assignment3
