CC := gcc
LDFLAGS := -Wall -Werror -g -O0
THREFLAG := -pthread

assigment1:	assigment1.c
	$(CC) $(LDFLAGS)  -o assigment1  assigment1.c
assigment2:	assigment2.c
	$(CC) $(LDFLAGS)  -o assigment2  assigment2.c
assigment3:	assigment3.c
	$(CC) $(LDFLAGS)  -o assigment3  assigment3.c

clean:
	rm -rf assigment1 assigment2 assigment3
